[props.str]
description = "string value prop."
type = "string"
[props.strMinMaxLength]
description = "string value prop with min / max length."
type = "string"
minLength = 1
maxLength = 256
[props.strRegex]
description = "string value prop with regex condition."
type = "string"
regex = "[a-Z]+"
[props.strArray]
description = "string array prop"
type = "string"
array = true
[props.uuid]
description = "UUID prop."
type = "uuid"
[props.email]
description = "Email prop."
type = "email"
[props.url]
type = "url"
[props.num]
type = "number"
[props.numArray]
type = "number"
array = true
[props.int]
type = "int"
[props.numMinMax]
type = "number"
min = -10
max = 10
[props.child]
type = "ref:./Child"
[props.children]
type = "ref:./Child"
array = true
