// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.

import Child from "./Child.model"

export class ParseError extends Error {
  constructor (message: string) {
    super("parseChild ParseError: " + message)
  }
}

export default function parseChild (data: any) {
  if (typeof data !== "object") {
    throw new ParseError("Given data is not an object. " + String(data))
  }
  const id: string = data["id"]
  if (typeof id !== "string") {
    throw new ParseError("id is not a string")
  }
  const name: string = data["name"]
  if (typeof name !== "string") {
    throw new ParseError("name is not a string")
  }
  const school: string = data["school"]
  if (typeof school !== "string") {
    throw new ParseError("school is not a string")
  }
  return new Child(
    id,
    name,
    school,
  )
}
