// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.

import Example from "./Example.model"

export class ParseError extends Error {
  constructor (message: string) {
    super("parseExample ParseError: " + message)
  }
}

export default function parseExample (data: any) {
  if (typeof data !== "object") {
    throw new ParseError("Given data is not an object. " + String(data))
  }
  const id: string = data["id"]
  if (typeof id !== "string") {
    throw new ParseError("id is not a string")
  }
  const name: string = data["name"]
  if (typeof name !== "string") {
    throw new ParseError("name is not a string")
  }
  const age: number = data["age"]
  if (typeof age !== "number") {
    throw new ParseError("age is not a number")
  }
  const height: number = data["height"]
  if (typeof height !== "number") {
    throw new ParseError("height is not a number")
  }
  const isAlien: boolean = data["isAlien"]
  if (typeof isAlien !== "boolean") {
    throw new ParseError("isAlien is not a boolean")
  }
  return new Example(
    id,
    name,
    age,
    height,
    isAlien,
  )
}
