// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.

import faker from "faker"
import Example from "./Example.model"

export class FakeError extends Error {
  constructor (message: string) {
    super("fakeExample FakeError: " + message)
  }
}

export default function fakeExample (data?: any): Example {
  if (data && typeof data !== "object") {
    throw new FakeError("Given data is not an object. " + String(data))
  }
  const id: string = data["id"] || faker.random.uuid()
  if (typeof id !== "string") {
    throw new FakeError("id is not a string")
  }
  const name: string = data["name"] || faker.name.findName()
  if (typeof name !== "string") {
    throw new FakeError("name is not a string")
  }
  const age: number = data["age"] || faker.random.number()
  if (typeof age !== "number") {
    throw new FakeError("age is not a number")
  }
  const height: number = data["height"] || faker.random.number()
  if (typeof height !== "number") {
    throw new FakeError("height is not a number")
  }
  const isAlien: boolean = data["isAlien"] || faker.random.boolean()
  if (typeof isAlien !== "boolean") {
    throw new FakeError("isAlien is not a boolean")
  }
  return new Example(
    id,
    name,
    age,
    height,
    isAlien,
  )
}
