description = "Str class with various formats."

[props.str]
description = "string value prop."
type = "string"
[props.strMinMaxLength]
description = "string value prop with min / max length."
type = "string"
minLength = 2
maxLength = 8
[props.strRegex]
description = "string value prop with regex condition."
type = "string"
regex = "^[a-z]+$"
[props.strArray]
description = "string array prop"
type = "string"
array = true
[props.strCandidates]
description = "string candidates prop"
type = "string"
candidates = ["apple", "banana"]
[props.uuid]
description = "UUID prop."
type = "uuid"
[props.email]
description = "Email prop."
type = "email"
[props.url]
type = "url"
