name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test-import-by-anohter-package:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: ["12", "14"]
        os: [windows-latest, macos-latest, ubuntu-latest]
    name: Tests importing by another package on Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install npm packages in dev
        run: yarn install
        working-directory: dev
      - name: chmod
        run: chmod +x build.sh
        working-directory: dev
      - name: Build modelgun
        run: yarn build
        working-directory: dev
      - name: Install npm packages in another package
        run: yarn install
        working-directory: test
      - name: Generates files
        run: yarn gen
        working-directory: test
      - name: Tests
        run: yarn test
        working-directory: test
