name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test-import-by-anohter-package:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ "12", "14" ]
    name: Tests importing by another package on Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install npm packages
        run: yarn install
        working-directory: test
      - name: Install npm packages in dev
        run: yarn install
        working-directory: dev
      - name: Build modelgun
        run: yarn build
        working-directory: dev
      - name: Install npm packages in another package
        run: yarn install
        working-directory: test
      - name: Run tests
        run: yarn test
        working-directory: test
